### PR TITLE
chore: apiextensions.k8s.io/v1

### PR DESCRIPTION
**Pull request by jsoref**
Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

This PR is because https://github.com/argoproj/argo-helm/pull/525 and https://github.com/argoproj/argo-helm/pull/563 and https://github.com/argoproj/argo-helm/pull/565 all fail because of this.

### CODE REVIEW

**Comment by jsoref** [comment]
I suspect that the current failure would require something like @alexmt 's https://github.com/argoproj/argo-cd/pull/1773

**Comment by whynowy** [comment]
What you should do is updating https://github.com/argoproj/argo-events/blob/master/hack/crdgen.sh instead of making changes to generated files directly.

**Comment by whynowy** [comment]
@jsoref - would you like to continue working on this or me to take it over?

**Comment by jsoref** [comment]
@whynowy Please be my guest

**Comment by whynowy** [comment]
https://github.com/argoproj/argo-events/pull/1054

**Pull request closed without merging**
