### PR TITLE
feat: Support dataTemplate and contextTemplate for Trigger Parameters

### PR DESCRIPTION
**Pull request by tinyzimmer**
This PR relates to the issue I opened:  #541 

One thing I am definitely open to maybe doing is maybe a number on `ResolveParamValue`. With the two additions it feels like it's getting a bit unruly. 

I can add some coverage as well. So consider this just a WIP to get feedback on the approach.

As a side note, I am having trouble running `make codegen`

```
./hack/update-api-docs.sh
I0315 18:03:19.811707    6828 main.go:127] parsing go packages in directory github.com/argoproj/argo-events/pkg/apis/eventsources/v1alpha1
F0315 18:03:21.224675    6828 main.go:133] no API packages found in github.com/argoproj/argo-events/pkg/apis/eventsources/v1alpha1
```

But that doesn't seem right...

### CODE REVIEW

**Comment by tinyzimmer** [comment]
> 1. You may need to run `make codegen` and commit updated files for deep copy and api docs.

I feel like an idiot, but I'm still struggling with this. On my mac it gives the error I showed above once it's done *allegedly* running deep copy funcs (that dont produce any changes).

Tried on Linux, and it ran all the way through, but again didn't actually generate any deep-copy code, and for the html/md files it just converted every kind to it's full path...e.g.

```diff
-<code>context</code></br> <em> Argo Events common.EventContext </em>
+<code>event</code></br> <em>
+github.com/argoproj/argo-events/pkg/apis/common.Event </em>
```

This is beginning to make me doubt my sanity. 

> 2. Can you also add an example sensor YAML file under `examples/sensors` folder that demonstrates the templating functionality?

I will add an example if not tonight, then sometime in the morning.

**Comment by tinyzimmer** [comment]
> Changes look good to me. I'll fix the `make codegen` part.

I'd be very curious what the issue was in case I want to contribute more in the future 😄

**Comment by VaibhavPage** [comment]
As you have introduced string fields within an existing struct, the deep-copy script won't update anything. But, `make codegen` should at least update API docs under `api` folder and openapi_generated.go file.  `make codegen` really just runs 1) https://github.com/argoproj/argo-events/blob/master/hack/update-codegen.sh 2) https://github.com/argoproj/argo-events/blob/master/hack/update-openapigen.sh and 3) https://github.com/argoproj/argo-events/blob/master/hack/update-api-docs.sh under the hood. So, you can run these files individually as well.

**Comment by VaibhavPage** [comment]
Also, can you resolve the conflicts? Thanks.

**Pull request merged**
