### PR TITLE
fix: eventsource: deterministic volume/volumeMount order

### PR DESCRIPTION
**Pull request by popsu**
The order was non-deterministic earlier and this caused the controller to change the deployment on every reconcile until it the order happened to be same twice in a row.

Fixes: https://github.com/argoproj/argo-events/issues/2810

I've tested this by making the change to `v1.7.1` tag (since we were running `v1.7.1` when I made the fix), building the image, and deploying it and the issue went away. 

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by popsu** [comment]
Let me know if there's something missing, first time doing PR here :bow:

**Comment by popsu** [comment]
https://github.com/argoproj/argo-events/blob/v1.8.1/common/util.go#L395-L417

I wonder if I should make the change in these functions instead? I don't know the codebase, so not sure at what level should the fix be made.

**Comment by whynowy** [comment]
@popsu - thanks for submitting the PR! Could you also add the same logic in the sensor controller?

**Comment by popsu** [comment]
I tried adding `make codegen`, but it failed:

```shell
2023/09/25 14:07:48 google/protobuf/descriptor.proto: File not found.                                                                                                                                                                                                                     
github.com/gogo/protobuf/gogoproto/gogo.proto:32:1: Import "google/protobuf/descriptor.proto" was not found or had errors.                                                                                                                                                                
github.com/gogo/protobuf/gogoproto/gogo.proto:38:8: "google.protobuf.EnumOptions" is not defined.                                                                                                                                                                                         
github.com/gogo/protobuf/gogoproto/gogo.proto: "google.protobuf.EnumOptions" is not defined.    
[... similar rows sniped...]
github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/intstr/generated.proto:23:1: Import "github.com/gogo/protobuf/gogoproto/gogo.proto" was not found or had errors.
2023/09/25 14:07:48 protoc -I . -I /tmp/tmp.evfHAmKZF6/src -I ./vendor --gogo_out=/tmp/tmp.evfHAmKZF6/src /tmp/tmp.evfHAmKZF6/src/github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/util/intstr/generated.proto
2023/09/25 14:07:48 Unable to generate protoc on k8s.io.apimachinery.pkg.util.intstr: exit status 1
Makefile:135: recipe for target 'codegen' failed
make: *** [codegen] Error                                 
```

I installed `protoc` from https://github.com/protocolbuffers/protobuf/releases. I'm using Linux so didn't use brew.

**Comment by popsu** [comment]
:heavy_check_mark: added the same sorting for Sensor deployment.

I'm not sure if the Sensor spec has any place (I didn't find with quick look) where the same bug could occur. Since the bug in `EventSource` case was due to storing webhooks (and other eventsources) in a Map and then when creating volume/volumemounts for the secrets the code iterates through the map and in Go the order is arbitrary.

If there is similar place in Sensor then the testcase I added should be modified (like the one I added for `EventSource` has.

**Review by whynowy — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
