### PR TITLE
feat(trigger): add log.intervalSeconds

### PR DESCRIPTION
**Pull request by alexec**
Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by alexec** [comment]
@whynowy @VaibhavPage I've had trouble testing this. Every time I create a log sensor, something edits the YAML and removes the `intervalSeconds`. Rather than grind away trying to figure it out - can you pleas ehelp?

**Comment by whynowy** [comment]
Need to resolve the conflict.

**Comment by alexec** [comment]
lint failure unrelated to PR

**Review by whynowy — APPROVED** [review]
LGTM

**Pull request merged**
