### PR TITLE
Fix codegen

### PR DESCRIPTION
**Pull request by dtaniwaki**
I can't execute `make codegen` successfully because of many reasons. I'm trying to fix it.

### CODE REVIEW

**Comment by dtaniwaki** [comment]
I'm still having the following error.

<details><summary>log</summary>

```
argo-events dtaniwaki [fix-codegen] $ GOPATH=~/github make codegen
./hack/update-codegen.sh
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+ '[' 6 -lt 4 ']'
+ '[' deepcopy,client,informer,lister == --help ']'
+ GENS=deepcopy,client,informer,lister
+ OUTPUT_PKG=github.com/argoproj/argo-events/pkg/client/sensor
+ APIS_PKG=github.com/argoproj/argo-events/pkg/apis
+ GROUPS_WITH_VERSIONS=sensor:v1alpha1
+ shift 4
++ dirname ./hack/../vendor/k8s.io/code-generator//generate-groups.sh
++ dirname ./hack/../vendor/k8s.io/code-generator//generate-groups.sh
++ dirname ./hack/../vendor/k8s.io/code-generator//generate-groups.sh
++ dirname ./hack/../vendor/k8s.io/code-generator//generate-groups.sh
++ dirname ./hack/../vendor/k8s.io/code-generator//generate-groups.sh
+ go install ././hack/../vendor/k8s.io/code-generator/cmd/defaulter-gen ././hack/../vendor/k8s.io/code-generator/cmd/client-gen ././hack/../vendor/k8s.io/code-generator/cmd/lister-gen ././hack/../vendor/k8s.io/code-generator/cmd/informer-gen ././hack/../vendor/k8s.io/code-generator/cmd/deepcopy-gen
+ FQ_APIS=()
+ for GVs in ${GROUPS_WITH_VERSIONS}
+ IFS=:
+ read G Vs
+ for V in ${Vs//,/ }
+ FQ_APIS+=(${APIS_PKG}/${G}/${V})
+ '[' deepcopy,client,informer,lister = all ']'
+ grep -qw deepcopy
+ echo 'Generating deepcopy funcs'
Generating deepcopy funcs
++ codegen::join , github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1
++ local IFS=,
++ shift
++ echo github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1
+ /Users/dtaniwaki/github/bin/deepcopy-gen --input-dirs github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1 -O zz_generated.deepcopy --bounding-dirs github.com/argoproj/argo-events/pkg/apis --go-header-file ./hack/../hack/custom-boilerplate.go.txt
+ '[' deepcopy,client,informer,lister = all ']'
+ grep -qw client
+ echo 'Generating clientset for sensor:v1alpha1 at github.com/argoproj/argo-events/pkg/client/sensor/clientset'
Generating clientset for sensor:v1alpha1 at github.com/argoproj/argo-events/pkg/client/sensor/clientset
++ codegen::join , github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1
++ local IFS=,
++ shift
++ echo github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1
+ /Users/dtaniwaki/github/bin/client-gen --clientset-name versioned --input-base '' --input github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1 --output-package github.com/argoproj/argo-events/pkg/client/sensor/clientset --go-header-file ./hack/../hack/custom-boilerplate.go.txt
+ '[' deepcopy,client,informer,lister = all ']'
+ grep -qw lister
+ echo 'Generating listers for sensor:v1alpha1 at github.com/argoproj/argo-events/pkg/client/sensor/listers'
Generating listers for sensor:v1alpha1 at github.com/argoproj/argo-events/pkg/client/sensor/listers
++ codegen::join , github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1
++ local IFS=,
++ shift
++ echo github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1
+ /Users/dtaniwaki/github/bin/lister-gen --input-dirs github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1 --output-package github.com/argoproj/argo-events/pkg/client/sensor/listers --go-header-file ./hack/../hack/custom-boilerplate.go.txt
+ '[' deepcopy,client,informer,lister = all ']'
+ grep -qw informer
+ echo 'Generating informers for sensor:v1alpha1 at github.com/argoproj/argo-events/pkg/client/sensor/informers'
Generating informers for sensor:v1alpha1 at github.com/argoproj/argo-events/pkg/client/sensor/informers
++ codegen::join , github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1
++ local IFS=,
++ shift
++ echo github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1
+ /Users/dtaniwaki/github/bin/informer-gen --input-dirs github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1 --versioned-clientset-package github.com/argoproj/argo-events/pkg/client/sensor/clientset/versioned --listers-package github.com/argoproj/argo-events/pkg/client/sensor/listers --output-package github.com/argoproj/argo-events/pkg/client/sensor/informers --go-header-file ./hack/../hack/custom-boilerplate.go.txt
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+ '[' 6 -lt 4 ']'
+ '[' deepcopy,client,informer,lister == --help ']'
+ GENS=deepcopy,client,informer,lister
+ OUTPUT_PKG=github.com/argoproj/argo-events/pkg/client/gateway
+ APIS_PKG=github.com/argoproj/argo-events/pkg/apis
+ GROUPS_WITH_VERSIONS=gateway:v1alpha1
+ shift 4
++ dirname ./hack/../vendor/k8s.io/code-generator//generate-groups.sh
++ dirname ./hack/../vendor/k8s.io/code-generator//generate-groups.sh
++ dirname ./hack/../vendor/k8s.io/code-generator//generate-groups.sh
++ dirname ./hack/../vendor/k8s.io/code-generator//generate-groups.sh
++ dirname ./hack/../vendor/k8s.io/code-generator//generate-groups.sh
+ go install ././hack/../vendor/k8s.io/code-generator/cmd/defaulter-gen ././hack/../vendor/k8s.io/code-generator/cmd/client-gen ././hack/../vendor/k8s.io/code-generator/cmd/lister-gen ././hack/../vendor/k8s.io/code-generator/cmd/informer-gen ././hack/../vendor/k8s.io/code-generator/cmd/deepcopy-gen
+ FQ_APIS=()
+ for GVs in ${GROUPS_WITH_VERSIONS}
+ IFS=:
+ read G Vs
+ for V in ${Vs//,/ }
+ FQ_APIS+=(${APIS_PKG}/${G}/${V})
+ '[' deepcopy,client,informer,lister = all ']'
+ grep -qw deepcopy
+ echo 'Generating deepcopy funcs'
Generating deepcopy funcs
++ codegen::join , github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1
++ local IFS=,
++ shift
++ echo github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1
+ /Users/dtaniwaki/github/bin/deepcopy-gen --input-dirs github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1 -O zz_generated.deepcopy --bounding-dirs github.com/argoproj/argo-events/pkg/apis --go-header-file ./hack/../hack/custom-boilerplate.go.txt
+ '[' deepcopy,client,informer,lister = all ']'
+ grep -qw client
+ echo 'Generating clientset for gateway:v1alpha1 at github.com/argoproj/argo-events/pkg/client/gateway/clientset'
Generating clientset for gateway:v1alpha1 at github.com/argoproj/argo-events/pkg/client/gateway/clientset
++ codegen::join , github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1
++ local IFS=,
++ shift
++ echo github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1
+ /Users/dtaniwaki/github/bin/client-gen --clientset-name versioned --input-base '' --input github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1 --output-package github.com/argoproj/argo-events/pkg/client/gateway/clientset --go-header-file ./hack/../hack/custom-boilerplate.go.txt
+ '[' deepcopy,client,informer,lister = all ']'
+ grep -qw lister
+ echo 'Generating listers for gateway:v1alpha1 at github.com/argoproj/argo-events/pkg/client/gateway/listers'
Generating listers for gateway:v1alpha1 at github.com/argoproj/argo-events/pkg/client/gateway/listers
++ codegen::join , github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1
++ local IFS=,
++ shift
++ echo github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1
+ /Users/dtaniwaki/github/bin/lister-gen --input-dirs github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1 --output-package github.com/argoproj/argo-events/pkg/client/gateway/listers --go-header-file ./hack/../hack/custom-boilerplate.go.txt
+ '[' deepcopy,client,informer,lister = all ']'
+ grep -qw informer
+ echo 'Generating informers for gateway:v1alpha1 at github.com/argoproj/argo-events/pkg/client/gateway/informers'
Generating informers for gateway:v1alpha1 at github.com/argoproj/argo-events/pkg/client/gateway/informers
++ codegen::join , github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1
++ local IFS=,
++ shift
++ echo github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1
+ /Users/dtaniwaki/github/bin/informer-gen --input-dirs github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1 --versioned-clientset-package github.com/argoproj/argo-events/pkg/client/gateway/clientset/versioned --listers-package github.com/argoproj/argo-events/pkg/client/gateway/listers --output-package github.com/argoproj/argo-events/pkg/client/gateway/informers --go-header-file ./hack/../hack/custom-boilerplate.go.txt
./hack/generate-proto.sh
+ set -o errexit
+ set -o nounset
+ set -o pipefail
+++ dirname ./hack/generate-proto.sh
++ cd ./hack/..
++ pwd
+ PROJECT_ROOT=/Users/dtaniwaki/github/src/github.com/argoproj/argo-events
++ cd /Users/dtaniwaki/github/src/github.com/argoproj/argo-events
++ ls -d -1 ./vendor/k8s.io/code-generator
+ CODEGEN_PKG=./vendor/k8s.io/code-generator
+ PATH=/Users/dtaniwaki/github/src/github.com/argoproj/argo-events/dist:/Users/dtaniwaki/github/src/github.com/argoproj/argo-events/dist:/Users/dtaniwaki/.gvm/pkgsets/go1.11.4/argo-events/bin:/Users/dtaniwaki/.gvm/pkgsets/go1.11.4/argo-events/overlay/bin:/Users/dtaniwaki/.gvm/pkgsets/go1.11.4/argo-events/bin:/Users/dtaniwaki/.gvm/pkgsets/go1.11.4/global/bin:/Users/dtaniwaki/.gvm/gos/go1.11.4/bin:/Users/dtaniwaki/.gvm/pkgsets/go1.11.4/global/overlay/bin:/Users/dtaniwaki/.gvm/bin:/Users/dtaniwaki/.gvm/bin:/usr/local/kubebuilder/bin:/Users/dtaniwaki/github/kubernetes/third_party/etcd:/Users/dtaniwaki/github/kubernetes/cluster:/Users/dtaniwaki/github/kubeadm-dind-cluster/fixed:/Users/dtaniwaki/github/kubeadm-dind-cluster:/Users/dtaniwaki/go/bin/:/Users/dtaniwaki/.jenv/shims:/Users/dtaniwaki/.pyenv/shims:/Users/dtaniwaki/.nodenv/shims:/Users/dtaniwaki/.rbenv/shims:/Users/dtaniwaki/.pyenv/bin:/Users/dtaniwaki/bin/:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/usr/local/opt/openssl/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/MacGPG2/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/dtaniwaki/go/bin/:/Users/dtaniwaki/.jenv/shims:/Users/dtaniwaki/.pyenv/shims:/Users/dtaniwaki/.nodenv/shims:/Users/dtaniwaki/.rbenv/shims:/Users/dtaniwaki/.pyenv/bin:/Users/dtaniwaki/bin/:/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/bin:/usr/local/opt/openssl/bin:/usr/local/bin/scala/bin:/Users/dtaniwaki/bin:/Users/dtaniwaki/github/dotfiles/git/scripts:node_modules/.bin:/usr/local/bin/scala/bin:/usr/local/bin:/Users/dtaniwaki/bin:/Users/dtaniwaki/github/dotfiles/git/scripts:node_modules/.bin:/bin:/Users/dtaniwaki/bin
+ go build -i -o dist/go-to-protobuf ./vendor/k8s.io/code-generator/cmd/go-to-protobuf
+ go build -i -o dist/protoc-gen-gogo ./vendor/k8s.io/code-generator/cmd/go-to-protobuf/protoc-gen-gogo
+ PACKAGES=(github.com/argoproj/argo-events/pkg/apis/common github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1 github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1)
+ APIMACHINERY_PKGS=(+k8s.io/apimachinery/pkg/util/intstr +k8s.io/apimachinery/pkg/api/resource +k8s.io/apimachinery/pkg/runtime/schema +k8s.io/apimachinery/pkg/runtime k8s.io/apimachinery/pkg/apis/meta/v1 k8s.io/api/core/v1)
+++ IFS=,
+++ echo github.com/argoproj/argo-events/pkg/apis/common,github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1,github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1
+++ IFS=,
+++ echo +k8s.io/apimachinery/pkg/util/intstr,+k8s.io/apimachinery/pkg/api/resource,+k8s.io/apimachinery/pkg/runtime/schema,+k8s.io/apimachinery/pkg/runtime,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/api/core/v1
++ go run /Users/dtaniwaki/github/src/github.com/argoproj/argo-events/vendor/k8s.io/code-generator/cmd/go-to-protobuf/main.go --logtostderr --go-header-file=/Users/dtaniwaki/github/src/github.com/argoproj/argo-events/hack/custom-boilerplate.go.txt --packages=github.com/argoproj/argo-events/pkg/apis/common,github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1,github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1 --apimachinery-packages=+k8s.io/apimachinery/pkg/util/intstr,+k8s.io/apimachinery/pkg/api/resource,+k8s.io/apimachinery/pkg/runtime/schema,+k8s.io/apimachinery/pkg/runtime,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/api/core/v1 --proto-import=./vendor
2019/03/10 20:06:04 github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/api/resource/generated.proto: warning: Import k8s.io/apimachinery/pkg/util/intstr/generated.proto but not used.
2019/03/10 20:06:04 github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/runtime/schema/generated.proto: warning: Import k8s.io/apimachinery/pkg/util/intstr/generated.proto but not used.
2019/03/10 20:06:05 github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/runtime/generated.proto: warning: Import k8s.io/apimachinery/pkg/util/intstr/generated.proto but not used.
2019/03/10 20:06:05 github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto: warning: Import k8s.io/apimachinery/pkg/util/intstr/generated.proto but not used.
github.com/argoproj/argo-events/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto: warning: Import k8s.io/apimachinery/pkg/runtime/schema/generated.proto but not used.
2019/03/10 20:06:08 github.com/argoproj/argo-events/vendor/k8s.io/api/core/v1/generated.proto: warning: Import k8s.io/apimachinery/pkg/runtime/schema/generated.proto but not used.
2019/03/10 20:06:13 github.com/argoproj/argo-events/pkg/apis/common/generated.proto: warning: Import k8s.io/apimachinery/pkg/util/intstr/generated.proto but not used.
github.com/argoproj/argo-events/pkg/apis/common/generated.proto: warning: Import k8s.io/apimachinery/pkg/runtime/generated.proto but not used.
2019/03/10 20:06:14 github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1/generated.proto: warning: Import k8s.io/apimachinery/pkg/util/intstr/generated.proto but not used.
github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1/generated.proto: warning: Import k8s.io/apimachinery/pkg/runtime/schema/generated.proto but not used.
github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1/generated.proto: warning: Import k8s.io/apimachinery/pkg/runtime/generated.proto but not used.
2019/03/10 20:06:15 github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1/generated.proto: warning: Import k8s.io/apimachinery/pkg/runtime/schema/generated.proto but not used.
github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1/generated.proto: warning: Import k8s.io/apimachinery/pkg/runtime/generated.proto but not used.
github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1/generated.proto: warning: Import k8s.io/apimachinery/pkg/util/intstr/generated.proto but not used.
github.com/argoproj/argo-events/pkg/apis/gateway/v1alpha1/generated.proto: warning: Import github.com/argoproj/argo-events/pkg/apis/sensor/v1alpha1/generated.proto but not used.
+ protoc -I=/Users/dtaniwaki/github/src --doc_out=../docs --doc_opt=markdown,gateway-protocol.md pkg/apis/gateway/v1alpha1/generated.proto
pkg/apis/gateway/v1alpha1/generated.proto: File does not reside within any path specified using --proto_path (or -I).  You must specify a --proto_path which encompasses this file.  Note that the proto_path must be an exact prefix of the .proto file names -- protoc is too dumb to figure out when two paths (e.g. absolute and relative) are equivalent (it's harder than you think).
make: *** [protogen] Error 1
```

</details>

**Comment by VaibhavPage** [comment]
Ok. can you change the protoc commands that generates documentations and add 
```
-I . \
  -I ${GOPATH}/src \
  -I ${GOPATH}/src/github.com/argoproj/argo-events
```

to it?

If that doesn't work, lets comment these lines for now. I'll add the fix later.

**Comment by dtaniwaki** [comment]
I commented out the last 2 commands of `hack/generate-proto.sh` because I can't make it succeeded.

**Comment by dtaniwaki** [comment]
And I also found the generated go files are very different from the original like below.

```diff
diff --git a/pkg/apis/gateway/v1alpha1/generated.pb.go b/pkg/apis/gateway/v1alpha1/generated.pb.go
index a14fedd..d7e1a2d 100644
--- a/pkg/apis/gateway/v1alpha1/generated.pb.go
+++ b/pkg/apis/gateway/v1alpha1/generated.pb.go
@@ -17,19 +17,21 @@ limitations under the License.

 package v1alpha1

-import proto "github.com/gogo/protobuf/proto"
-import fmt "fmt"
-import math "math"
-import common "github.com/argoproj/argo-events/pkg/apis/common"
+import (
+       fmt "fmt"

-import v11 "k8s.io/api/core/v1"
+       common "github.com/argoproj/argo-events/pkg/apis/common"

-import github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
+       io "io"

-import strings "strings"
-import reflect "reflect"
+       proto "github.com/gogo/protobuf/proto"
+       github_com_gogo_protobuf_sortkeys "github.com/gogo/protobuf/sortkeys"
+       v11 "k8s.io/api/core/v1"

-import io "io"
+       math "math"
+       reflect "reflect"
+       strings "strings"
+)

 // Reference imports to suppress errors if they are not otherwise used.
 var _ = proto.Marshal
@@ -45,7 +47,7 @@ const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package
 func (m *Gateway) Reset()      { *m = Gateway{} }
 func (*Gateway) ProtoMessage() {}
 func (*Gateway) Descriptor() ([]byte, []int) {
-       return fileDescriptor_generated_d7e7992cb16da963, []int{0}
...
```

Maybe, it's because of protoc version difference.

**Comment by VaibhavPage** [comment]
Thats fine i guess

**Comment by magaldima** [comment]
what's version of protoc are you using?

**Comment by dtaniwaki** [comment]
I use 3.6.1.

**Comment by dtaniwaki** [comment]
CI failed... Could you restart it? I think I need to add more wait for sync in the operator tests.

**Pull request merged**
