### PR TITLE
docs: MinIO event source link updated in docs

### PR DESCRIPTION
**Pull request by xi2817-aajgaonkar**
Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by xi2817-aajgaonkar** [comment]
@alexec please check this

**Review by whynowy — CHANGES_REQUESTED** [review]
We should use the URL below, could you change it?

https://argoproj.github.io/argo-events/eventsources/setup/minio/

**Comment by xi2817-aajgaonkar** [comment]
@whynowy done

**Review by whynowy — APPROVED** [review]
Thanks for fixing it!

**Pull request merged**
