### PR TITLE
fix: Limit github hooks manager daemon lifetime to 10 min

### PR DESCRIPTION
**Pull request by ibabiankou**
Fixes https://github.com/argoproj/argo-events/issues/1929

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Review by whynowy — COMMENTED** [review]
There's one case:

1. `DeleteHookOnFinish` was `true`;
2. `DeleteHookOnFinish` was updated to `false`
3. The new old will come up before the old pod gets terminated, which means the hook will be deleted but nobody fixes it.

I'm okay with ignoring this corner case if the rate limit is a big concern. What do you think?

**Comment by ibabiankou** [comment]
Ah, very nice! I didn't think about that case 🤔 If that happens, restarting the pod would fix the issue. But that is not obvious to an operator.

Given that the race condition is only relevant first minutes of the pod lifetime, an alternative could be to simply limit the duration the daemon is alive. Let's say run it for 10 minutes.

**Comment by ibabiankou** [comment]
@whynowy I've updated the PR to simply do 10 iterations, which should cover the case you described. Please let me know if there is anything else I should do to get this PR merged 😊

**Review by whynowy — COMMENTED** [review]
@daniel-codefresh - do you see if there's any issue with this?

**Comment by daniel-codefresh** [comment]
> @daniel-codefresh - do you see if there's any issue with this?

I think we should be fine with a 10 mins daemon lifetime 👍

**Review by whynowy — APPROVED** [review]
Thanks!

**Comment by Piroddi** [comment]
@ibabiankou correct me if I'm wrong. But does this the daemon only runs for 10minutes? So if after 10 minutes someone deletes the webhook manually, it will only be recreated once this pod restarts ?

**Comment by whynowy** [comment]
@ibabiankou @daniel-codefresh @Piroddi - per the link below, the rate limit is 5,000 per hour, is that correct? If that's the case, 1 request/min shouldn't be a big deal. Did I miss anything?

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-personal-accounts

**Comment by whynowy** [comment]
@ibabiankou @daniel-codefresh @Piroddi - per the link below, the rate limit is 5,000 per hour, is that correct? If that's the case, 1 request/min shouldn't be a big deal. Did I miss anything?

https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-personal-accounts

**Comment by Stephan202** [comment]
(Colleague of @ibabiankou here:) @whynowy IIRC there's one such polling process per Github repository, and we have many of those, with more on the way.

**Comment by whynowy** [comment]
> @whynowy we still using the v1.6 (Nats Streaming), therefore we needed 4 webhooks per repo across 25 repos (4 * 25 * 60 = 6000/hr). So we are getting rate-limited by Github.
> 
> Its looks like this PR just loops once a minute for 10 minutes then it stops. My worry is that if someone accidentally changes the webhook manually after the initial 10 min it will never be reconciled (I could be wrong through :) )
> 
> What about if we made the timer an ENV variable that the user can override (can leave default as 60s). I'm currently running a fork of argo-events which only loops once an hour.

Sorry I have missed the discussion here. I think making it configurable is an option.

**Pull request merged**
