### PR TITLE
fix: Sensor triggers an Argo Workflow with wrong name

### PR DESCRIPTION
**Pull request by daniel-codefresh**
Signed-off-by: Daniel Soifer <daniel.soifer@codefresh.io>

### CODE REVIEW

**Comment by daniel-codefresh** [comment]
Fixes: #1511

**Comment by daniel-codefresh** [comment]
Context:
In some cases `src.Value` pointer was returned from `ResolveParamValue` function and the `ApplyParams` function was dereferencing this pointer and changing its value: 
https://github.com/argoproj/argo-events/blob/f91e05905ae55094912ff1153b80fd3736db7727/sensors/triggers/params.go#L112
Due to this reason, the original default value that was set by the user was overridden which of course effected the next actions that were triggered by the same sensor.

**Comment by whynowy** [comment]
> Context: In some cases `src.Value` pointer was returned by `ResolveParamValue` and then the `ApplyParams` function was dereferencing this pointer and changing its value:
> 
> https://github.com/argoproj/argo-events/blob/f91e05905ae55094912ff1153b80fd3736db7727/sensors/triggers/params.go#L112
> 
> 
> Due to this reason, the original default value that was set by the user was overridden which of course effected the next actions that were triggered by the same sensor.

Thanks @daniel-codefresh ! Do you mean this issue only happens when operation is set to append?

**Comment by daniel-codefresh** [comment]
> > Context: In some cases `src.Value` pointer was returned by `ResolveParamValue` and then the `ApplyParams` function was dereferencing this pointer and changing its value:
> > https://github.com/argoproj/argo-events/blob/f91e05905ae55094912ff1153b80fd3736db7727/sensors/triggers/params.go#L112
> > 
> > Due to this reason, the original default value that was set by the user was overridden which of course effected the next actions that were triggered by the same sensor.
> 
> Thanks @daniel-codefresh ! Do you mean this issue only happens when operation is set to append?

Prepend as well:
https://github.com/argoproj/argo-events/blob/f91e05905ae55094912ff1153b80fd3736db7727/sensors/triggers/params.go#L114

**Comment by whynowy** [comment]
> > > Context: In some cases `src.Value` pointer was returned by `ResolveParamValue` and then the `ApplyParams` function was dereferencing this pointer and changing its value:
> > > https://github.com/argoproj/argo-events/blob/f91e05905ae55094912ff1153b80fd3736db7727/sensors/triggers/params.go#L112
> > > 
> > > Due to this reason, the original default value that was set by the user was overridden which of course effected the next actions that were triggered by the same sensor.
> > 
> > 
> > Thanks @daniel-codefresh ! Do you mean this issue only happens when operation is set to append?
> 
> Prepend as well:
> 
> https://github.com/argoproj/argo-events/blob/f91e05905ae55094912ff1153b80fd3736db7727/sensors/triggers/params.go#L114

👍

**Review by whynowy — APPROVED** [review]

**Pull request merged**
