### PR TITLE
feat: Add `NotEqualTo` comparator to data filters

### PR DESCRIPTION
**Pull request by hisener**
Fixes https://github.com/argoproj/argo-events/issues/808.

### CODE REVIEW

**Comment by hisener** [comment]
I've already added `!=` there, see https://github.com/argoproj/argo-events/pull/822/files#diff-dad435d871038d7159bbe9a27fc214c1R53. What else do we need to change in that file?

**Comment by whynowy** [comment]
> I've already added `!=` there, see https://github.com/argoproj/argo-events/pull/822/files#diff-dad435d871038d7159bbe9a27fc214c1R53. What else do we need to change in that file?

Oh.... my bad!

**Comment by hisener** [comment]
I'll generate docs in an hour or so.

**Comment by hisener** [comment]
@whynowy I saw you merged this but I guess we had to [generate docs](https://github.com/argoproj/argo-events/blob/master/CONTRIBUTING.md#changing-types). Shall I create a separate PR to fix those?

Also, does the image with tag `1.647` on gcr.io contain this commit? If not, can you tag a new image?

**Comment by whynowy** [comment]
> @whynowy I saw you merged this but I guess we had to [generate docs](https://github.com/argoproj/argo-events/blob/master/CONTRIBUTING.md#changing-types). Shall I create a separate PR to fix those?
> 
> Also, does the image with tag `1.647` on gcr.io contain this commit? If not, can you tag a new image?

No worries, I can re-gun `codegen` together in another PR. 

The Image in gcr.io is just my personal repo for testing, we will cut 1.0 RC image soon.

**Pull request merged**
