### PR TITLE
fix: add git to argo-events image

### PR DESCRIPTION
**Pull request by tdenmon**
This commit adds `git` to the argo-events Docker image, which is required in order to use Git as a source for a Sensor.

Fixes [#3065](https://github.com/argoproj/argo-events/issues/3065)

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Review by tdenmon — COMMENTED** [review]
Copying the relevant linked libraries is not my ideal solution here, but as `git` is dynamically linked in the apk package it's either this or cloning down the `git` source code and manually building it statically linked.

This is the far faster solution. I'm open to suggestions/pushback here though.

**Comment by whynowy** [comment]
The `git` binary was even before my time. But I don't think we need it in the image - we use `go-git` lib, and it worked before. It went to a bad state due to some unknown changes. Need investigation.

**Comment by tdenmon** [comment]
> The `git` binary was even before my time. But I don't think we need it in the image - we use `go-git` lib, and it worked before. It went to a bad state due to some unknown changes. Need investigation.

Could be related to [go-git #838](https://github.com/go-git/go-git/issues/838)? There's a [refactor PR](https://github.com/go-git/go-git/pull/1111) to explicitly drop any dependency on an external git binary.

**Comment by whynowy** [comment]
> > The `git` binary was even before my time. But I don't think we need it in the image - we use `go-git` lib, and it worked before. It went to a bad state due to some unknown changes. Need investigation.
> 
> Could be related to [go-git #838](https://github.com/go-git/go-git/issues/838)? There's a [refactor PR](https://github.com/go-git/go-git/pull/1111) to explicitly drop any dependency on an external git binary.

Probably...

**Pull request closed without merging**
