### PR TITLE
feature: Add 'caCertificate' parameter to Minio EventSource

### PR DESCRIPTION
**Pull request by rossigee**
Allows private CA certificate to be specified for Minio EventSource.

Related to: https://github.com/argoproj/argo-events/issues/1027

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

(Not added to USERS, as I'm not an 'organization'. I'm just using this internally/privately for now).

### CODE REVIEW

**Comment by rossigee** [comment]
When I try to update the API docs it adds a ton of empty lines, tainting the patch...

```
diff --git a/api/event-bus.md b/api/event-bus.md
index d26fe55c..cbd93f37 100644
--- a/api/event-bus.md
+++ b/api/event-bus.md
@@ -1,536 +1,1007 @@
 <p>
+
 Packages:
+
 </p>
+
 <ul>
+
 <li>
+
 <a href="#argoproj.io%2fv1alpha1">argoproj.io/v1alpha1</a>
+
 </li>
...
```

Any suggestions?

**Comment by whynowy** [comment]
> When I try to update the API docs it adds a ton of empty lines, tainting the patch...
> 
> ```
> diff --git a/api/event-bus.md b/api/event-bus.md
> index d26fe55c..cbd93f37 100644
> --- a/api/event-bus.md
> +++ b/api/event-bus.md
> @@ -1,536 +1,1007 @@
>  <p>
> +
>  Packages:
> +
>  </p>
> +
>  <ul>
> +
>  <li>
> +
>  <a href="#argoproj.io%2fv1alpha1">argoproj.io/v1alpha1</a>
> +
>  </li>
> ...
> ```
> 
> Any suggestions?

I guess it's due to different doc-gen version.

**Comment by whynowy** [comment]
@rossigee - could you fix the DCO?

**Comment by rossigee** [comment]
DCO?

**Comment by whynowy** [comment]
> DCO?
> […](#)
> On Nov 14, 2023, 15:11, at 15:11, Derek Wang ***@***.***> wrote: @rossigee - could you fix the DCO? -- Reply to this email directly or view it on GitHub: [#2903 (comment)](https://github.com/argoproj/argo-events/pull/2903#issuecomment-1809719953) You are receiving this because you were mentioned. Message ID: ***@***.***>

Sign off your commit with `git commit -s xxxx`. Check the failed CI for the detail.

**Review by whynowy — APPROVED** [review]
Thanks!

**Pull request merged**
