### PR TITLE
fix: changing lastResetTime to a time.Time from int64 seconds so time comparison can occur at a finer granularity

### PR DESCRIPTION
**Pull request by juliev0**
Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by juliev0** [comment]
This is in reference to this bug: https://github.com/argoproj/argo-events/issues/1694

**Comment by juliev0** [comment]
I have tested this with the following conditions:
1. similar to bug: just one dependency in the condition and multiple webhooks curled immediately one after the other: verifying each is triggered in sensor
2.  conditional expression involving && and both webhooks are curled - verify sensor is triggered
3. standard condition reset case with conditional expression involving &&: verifying condition reset occurs
4. condition reset case where pod is down at the cron time

**Review by whynowy — APPROVED** [review]
LGTM, thanks for the quick fix!

**Comment by tooptoop4** [comment]
when is next release with this fix?

**Pull request merged**
