### PR TITLE
- changed webhook gateway example to include port on deployment

### PR DESCRIPTION
**Pull request by twiechert**
- adding container port based on service port in deployment of sensor

### CODE REVIEW

**Comment by VaibhavPage** [comment]
can we close this pr and #127?  these issues are addressed in v0.7

**Comment by VaibhavPage** [comment]
can we close this pr?

**Comment by magaldima** [comment]
is this stale? has this feature already been addressed @VaibhavPage ?

**Comment by VaibhavPage** [comment]
> is this stale? has this feature already been addressed @VaibhavPage ?

yup. this is already addressed in v0.7

**Pull request closed without merging**
