### PR TITLE
[issue-1863] username and password auth support for mqtt eventsource

### PR DESCRIPTION
**Pull request by premadk**
Signed-off-by: Prema devi Kuppuswamy <premadk@gmail.com>

Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Review by daniel-codefresh — APPROVED** [review]
LGTM! thanks

**Review by whynowy — APPROVED** [review]
Thanks!

**Comment by BebbiBraeu** [comment]
This doesn't work for me.
We just updated to argo-events 1.7.5.
But whenever I try to create a MQTT EventSource with credentials, "auth" just gets ignored and doesn't appear in the EventSource in the argo UI. Also when adding it in the UI, it gets deleted after the update.
I would guess that the schema validation fails.
Can this be checked somehow and how could this be fixed?

**Comment by whynowy** [comment]
> 

@BebbiBraeu - Can you create issue with what you found (please include the spec)?

**Pull request merged**
