### PR TITLE
Change log level for eventsource webhook

### PR DESCRIPTION
**Pull request by omerap12**
Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

Fixes: #3003 

Added the option to change log level for eventsource webhook. 
Tested manually with the following yaml files:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  webhook:
    example:
      endpoint: /example
      logLevel: info
      method: POST
      port: "12000"
      url: ""
```
will generate:
```json
{"level":"info","ts":1718303383.2417948,"logger":"argo-events.eventsource","caller":"cmd/start.go:63","msg":"starting eventsource server","eventSourceName":"webhook","version":"v1.9.0"}
{"level":"info","ts":1718303383.2418778,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:454","msg":"Starting event source server...","eventSourceName":"webhook"}
{"level":"info","ts":1718303383.2421641,"logger":"argo-events.eventsource","caller":"eventbus/driver.go:36","msg":"eventBusConfig: {NATS:&NATSConfig{URL:nats://eventbus-default-stan-svc:4222,ClusterID:*eventbus-default,Auth:*token,AccessSecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:eventbus-default-client,},Key:client-auth,Optional:nil,},} JetStream:nil Kafka:nil}","eventSourceName":"webhook"}
{"level":"info","ts":1718303383.242228,"logger":"argo-events.eventsource","caller":"base/stan.go:48","msg":"NATS auth strategy: Token","eventSourceName":"webhook","clientID":"client-webhook-eventsource-k9rpd-c6bdf4cc8-rp6j8-814"}
{"level":"info","ts":1718303383.2426295,"logger":"argo-events.eventsource","caller":"metrics/metrics.go:175","msg":"starting metrics server","eventSourceName":"webhook"}
{"level":"info","ts":1718303383.2444825,"logger":"argo-events.eventsource","caller":"base/stan.go:60","msg":"Connected to NATS server.","eventSourceName":"webhook","clientID":"client-webhook-eventsource-k9rpd-c6bdf4cc8-rp6j8-814"}
{"level":"info","ts":1718303383.2457066,"logger":"argo-events.eventsource","caller":"base/stan.go:73","msg":"Connected to NATS streaming server.","eventSourceName":"webhook","clientID":"client-webhook-eventsource-k9rpd-c6bdf4cc8-rp6j8-814"}
{"level":"info","ts":1718303383.2457209,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:603","msg":"Eventing server started.","eventSourceName":"webhook"}
{"level":"info","ts":1718303383.2457411,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:481","msg":"starting eventbus connection daemon...","eventSourceName":"webhook"}
{"level":"info","ts":1718303383.2458198,"logger":"argo-events.eventsource","caller":"webhook/start.go:157","msg":"started processing the webhook event source...","eventSourceName":"webhook","eventSourceType":"webhook","eventName":"example"}
{"level":"info","ts":1718303383.245832,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:214","msg":"validating the route...","eventSourceName":"webhook","eventSourceType":"webhook","eventName":"example"}
{"level":"info","ts":1718303383.2458577,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:220","msg":"listening to payloads for the route...","eventSourceName":"webhook","eventSourceType":"webhook","eventName":"example"}
{"level":"info","ts":1718303383.2458615,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:227","msg":"activating the route...","eventSourceName":"webhook","eventSourceType":"webhook","eventName":"example"}
{"level":"info","ts":1718303383.2459073,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:177","msg":"route is activated","eventSourceName":"webhook","eventSourceType":"webhook","eventName":"example","port":"12000","endpoint":"/example"}
{"level":"info","ts":1718303383.2459216,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:230","msg":"running operations post route activation...","eventSourceName":"webhook","eventSourceType":"webhook","eventName":"example"}
{"level":"info","ts":1718303405.4905033,"logger":"argo-events.eventsource","caller":"webhook/start.go:97","msg":"a request received, processing it...","eventSourceName":"webhook","eventSourceType":"webhook","eventName":"example","endpoint":"/example","port":"12000","http-method":"POST"}
{"level":"info","ts":1718303405.490834,"logger":"argo-events.eventsource","caller":"webhook/start.go:137","msg":"dispatching event on route's data channel...","eventSourceName":"webhook","eventSourceType":"webhook","eventName":"example","endpoint":"/example","port":"12000","http-method":"POST"}
{"level":"info","ts":1718303405.49086,"logger":"argo-events.eventsource","caller":"webhook/start.go:139","msg":"successfully processed the request","eventSourceName":"webhook","eventSourceType":"webhook","eventName":"example","endpoint":"/example","port":"12000","http-method":"POST"}
{"level":"info","ts":1718303405.4910479,"logger":"argo-events.eventsource","caller":"webhook/webhook.go:187","msg":"new event received, dispatching it...","eventSourceName":"webhook","eventSourceType":"webhook","eventName":"example"}
{"level":"info","ts":1718303405.495316,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:591","msg":"Succeeded to publish an event","eventSourceName":"webhook","eventName":"example","eventSourceType":"webhook","eventID":"38353339323465622d323230632d346131332d613864302d393738396163303061643762"}
```

and this yaml:
```yaml
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook
spec:
  service:
    ports:
    - port: 12000
      targetPort: 12000
  webhook:
    example:
      endpoint: /example
      logLevel: error
      method: POST
      port: "12000"
      url: ""
```
will generate:

```json
{"level":"info","ts":1718302957.5696802,"logger":"argo-events.eventsource","caller":"cmd/start.go:63","msg":"starting eventsource server","eventSourceName":"webhook","version":"latest+d967890.dirty"}
{"level":"info","ts":1718302957.572387,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:454","msg":"Starting event source server...","eventSourceName":"webhook"}
{"level":"info","ts":1718302957.5729907,"logger":"argo-events.eventsource","caller":"metrics/metrics.go:190","msg":"starting metrics server","eventSourceName":"webhook"}
{"time":"2024-06-13T18:22:37.573062218Z","level":"INFO","msg":"trying to resolve absolute path","path":"/etc/eventbus/auth"}
{"time":"2024-06-13T18:22:37.576902677Z","level":"INFO","msg":"adding path to search paths","path":"/etc/eventbus/auth"}
{"time":"2024-06-13T18:22:37.576994177Z","level":"INFO","msg":"attempting to read in config file"}
{"time":"2024-06-13T18:22:37.577108427Z","level":"INFO","msg":"searching for config in paths","paths":["/etc/eventbus/auth"]}
{"level":"info","ts":1718302957.5860682,"logger":"argo-events.eventsource","caller":"eventbus/driver.go:35","msg":"eventBusConfig: {NATS:&NATSConfig{URL:nats://eventbus-default-stan-svc:4222,ClusterID:*eventbus-default,Auth:*token,AccessSecret:&v1.SecretKeySelector{LocalObjectReference:LocalObjectReference{Name:eventbus-default-client,},Key:client-auth,Optional:nil,},} JetStream:nil Kafka:nil}","eventSourceName":"webhook"}
{"level":"info","ts":1718302957.5868874,"logger":"argo-events.eventsource","caller":"base/stan.go:48","msg":"NATS auth strategy: Token","eventSourceName":"webhook","clientID":"client-webhook-eventsource-k9rpd-864b5c69c5-5q8z6-924"}
{"level":"info","ts":1718302957.5997717,"logger":"argo-events.eventsource","caller":"base/stan.go:60","msg":"Connected to NATS server.","eventSourceName":"webhook","clientID":"client-webhook-eventsource-k9rpd-864b5c69c5-5q8z6-924"}
{"level":"info","ts":1718302957.603865,"logger":"argo-events.eventsource","caller":"base/stan.go:73","msg":"Connected to NATS streaming server.","eventSourceName":"webhook","clientID":"client-webhook-eventsource-k9rpd-864b5c69c5-5q8z6-924"}
{"level":"info","ts":1718302957.6039793,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:603","msg":"Eventing server started.","eventSourceName":"webhook"}
{"level":"info","ts":1718302957.604122,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:481","msg":"starting eventbus connection daemon...","eventSourceName":"webhook"}
{"level":"info","ts":1718302995.5472372,"logger":"argo-events.eventsource","caller":"eventsources/eventing.go:591","msg":"Succeeded to publish an event","eventSourceName":"webhook","eventName":"example","eventSourceType":"webhook","eventID":"31313834313666332d396137352d346439392d626239322d646536336466386161383965"}
```

As you can see no info from webhook.
Default is set to info.

### CODE REVIEW

**Comment by omerap12** [comment]
Friendly remainder :) @whynowy

**Comment by whynowy** [comment]
> Friendly remainder :) @whynowy

@omerap12 - thanks for raising the PR! Do you think it make sense to extend this capability to all the eventsources/sensors? for example, using an ENV variable to determine the log level?

**Comment by omerap12** [comment]
> > Friendly remainder :) @whynowy
> 
> @omerap12 - thanks for raising the PR! Do you think it make sense to extend this capability to all the eventsources/sensors? for example, using an ENV variable to determine the log level?

No problem. I agree that it makes sense to extend this to all the event sources and sensors. I can take this upon myself if you'd like :) .If you prefer not to add this to the types.go schema, we can use an ENV variable instead.

**Comment by whynowy** [comment]
> > > Friendly remainder :) @whynowy
> > 
> > 
> > @omerap12 - thanks for raising the PR! Do you think it make sense to extend this capability to all the eventsources/sensors? for example, using an ENV variable to determine the log level?
> 
> No problem. I agree that it makes sense to extend this to all the event sources and sensors. I can take this upon myself if you'd like :) .If you prefer not to add this to the types.go schema, we can use an ENV variable instead.

That will be awesome, thank you!

**Comment by omerap12** [comment]
Closing this PR, and creating a new one to support @whynowy request :)

**Pull request closed without merging**
