### PR TITLE
feat(sensor): disable leader election for jetstream eventbus

### PR DESCRIPTION
**Pull request by ryancurrah**
Supersedes https://github.com/argoproj/argo-events/pull/3240

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by whynowy** [comment]
What is the reason leader election is not needed when using jetstream? Assume the trigger relies on events from multiple sources, with multiple sensor instances, it will be an issue right?

**Comment by ryancurrah** [comment]
Leader election is not needed when using JetStream because, like Kafka consumer groups, it supports horizontal scaling through queue subscriptions, which distribute events across multiple sensor instances, ensuring that only one instance processes each event. Similar to how Kafka consumer groups ensure that each message is processed by only one consumer within a group, JetStream queue subscriptions achieve the same event distribution. Though it is required to ensure that queue subscriptions are enabled; otherwise, all sensor instances will receive and process the same events (If sensor leader election is turned off), leading to duplicate event processing.

Before disabling leader election for JetStream, I guess my PR should verify that the queue subscription is enabled to ensure events are handled by only one sensor instance.

Queue subscriptions were enabled in this commit https://github.com/argoproj/argo-events/commit/546129637287e7a4586333b840dbea55050c43b6.

**Comment by ryancurrah** [comment]
Leader election is not needed when using JetStream because, like Kafka consumer groups, it supports horizontal scaling through queue subscriptions, which distribute events across multiple sensor instances, ensuring that only one instance processes each event. Similar to Kafka consumer groups, where each message is processed by only one consumer within a group, JetStream queue subscriptions achieve the same event distribution. It is important to ensure that queue subscriptions are enabled; otherwise, if sensor leader election is turned off, all sensor instances will receive and process the same events, leading to duplicate event processing.

Before disabling leader election for JetStream, my PR should verify that queue subscriptions are enabled to ensure that events are handled by only one sensor instance.

Queue subscription support was added in this commit: https://github.com/argoproj/argo-events/commit/546129637287e7a4586333b840dbea55050c43b6.

**Comment by whynowy** [comment]
> Leader election is not needed when using JetStream because, like Kafka consumer groups, it supports horizontal scaling through queue subscriptions, which distribute events across multiple sensor instances, ensuring that only one instance processes each event. Similar to Kafka consumer groups, where each message is processed by only one consumer within a group, JetStream queue subscriptions achieve the same event distribution. It is important to ensure that queue subscriptions are enabled; otherwise, if sensor leader election is turned off, all sensor instances will receive and process the same events, leading to duplicate event processing.
> 
> Before disabling leader election for JetStream, my PR should verify that queue subscriptions are enabled to ensure that events are handled by only one sensor instance.
> 
> Queue subscription support was added in this commit: [5461296](https://github.com/argoproj/argo-events/commit/546129637287e7a4586333b840dbea55050c43b6).

This is not my concern. My concern is about the following scenario:

Sensor `s1` has dependencies on `es1 && es2`, with multiple sensor instances, those events can go to different pods, which will not be able to meet the `&&` condition.

**Comment by ryancurrah** [comment]
> This is not my concern. My concern is about the following scenario:
> 
> Sensor s1 has dependencies on es1 && es2, with multiple sensor instances, those events can go to different pods, which will not be able to meet the && condition.

Hrm how does it work for Kafka? I assume it would be the same.

**Comment by mweibel** [comment]
so this was closed but my earlier PR related to this (#3240) is still open. Any chance this could go further?

**Pull request closed without merging**
