### PR TITLE
fix: 1077 - JoinConversation for private channel throws method_not_supported_for_channel_type

### PR DESCRIPTION
**Pull request by shashwat-appdirect**
Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by whynowy** [comment]
Have you tested different use cases?

**Comment by shashwat-appdirect** [comment]
> Have you tested different use cases?

I am not sure how could I test it with the snapshot. Please suggest? Or maybe once it is merged and released, I'll test.
This change will affect only private channel which is anyways not working as of now also.

**Comment by whynowy** [comment]
> > Have you tested different use cases?
> 
> I am not sure how could I test it with the snapshot. Please suggest? Or maybe once it is merged and released, I'll test.
> This change will affect only private channel which is anyways not working as of now also.

Run `make sensor-image` to build an image, push to your own image registry and use it for testing.

**Comment by shashwat-appdirect** [comment]
> > > Have you tested different use cases?
> > 
> > 
> > I am not sure how could I test it with the snapshot. Please suggest? Or maybe once it is merged and released, I'll test.
> > This change will affect only private channel which is anyways not working as of now also.
> 
> Run `make sensor-image` to build an image, push to your own image registry and use it for testing.

Thanks a lot for the suggestion. I tried and was able to successfully test it. The message got posted into a private channel successfully. Please find the logs as below:

```
{"level":"info","ts":1613996036.2404935,"logger":"argo-events.sensor","caller":"slack/slack.go:84","msg":"executing SlackTrigger","sensorName":"webhook"}
{"level":"info","ts":1613996045.3540194,"logger":"argo-events.sensor","caller":"slack/slack.go:148","msg":"posting to channel...","sensorName":"webhook","channelName":"team-need4speed-auto"}
{"level":"info","ts":1613996045.651343,"logger":"argo-events.sensor","caller":"slack/slack.go:155","msg":"message successfully sent to channelID with timestamp","sensorName":"webhook","message":"This is a test message from ArgoCI","channelID":"GGM3QS8Q4","timestamp":"1613996045.002100"}
{"level":"info","ts":1613996045.6514304,"logger":"argo-events.sensor","caller":"slack/slack.go:156","msg":"finished executing SlackTrigger","sensorName":"webhook"}
{"level":"info","ts":1613996045.6514573,"logger":"argo-events.sensor","caller":"sensors/listener.go:284","msg":"successfully processed the trigger","sensorName":"webhook","triggerName":"slack-trigger","triggeredBy":["test-dep"]}

```
Also, tested for public channel and it is working fine.

**Review by whynowy — APPROVED** [review]
LGTM

**Pull request merged**
