### PR TITLE
fix(git-sensor): force fetch from git repository

### PR DESCRIPTION
**Pull request by rory-lamendola**
We've run into an issue with using the existing git sensor with our repository.  The sensor works for a while until it starts erroring on `failed to fetch. err: some refs were not updated`.  This seems to happen when we merge code to our repository, and our deploy process updates tags.  Updating tags on existing branches causes git to throw an error unless you force fetch.  The artifact already force fetches when given a particular ref, and I can't think of a downside of doing it everywhere given that you wouldn't be making local changes to branches in a sensor.

Fixes: #1120

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by whynowy** [comment]
I believe removing `cloneDirectory` will also fix your issue, but that will make it re-clone the repo every time when there's an event. Adding `force` seems to be reasonable to me. Is this PR ready for review?

**Comment by rory-lamendola** [comment]
@whynowy yeah, do you want me to fix the semantic pull request checker though?

**Comment by whynowy** [comment]
> @whynowy yeah, do you want me to fix the semantic pull request checker though?

No really, you are good.

**Review by whynowy — APPROVED** [review]
LGMT, thanks!

**Pull request merged**
