### PR TITLE
feat(webhook): add additional env vars

### PR DESCRIPTION
**Pull request by rdeusser**
I ran into an issue when deploying the Argo Events webhook where it was explicitly looking for a hardcoded deployment name. I wanted the ability to deploy it with a different name.

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by daniel-codefresh** [comment]
LGTM, thanks!
Could you please fix the DCO check by following the [instructions](https://github.com/argoproj/argo-events/pull/2356/checks?check_run_id=10101893073)?

**Review by daniel-codefresh — APPROVED** [review]
LGTM, thanks!
Could you please fix the DCO check by following the [instructions](https://github.com/argoproj/argo-events/pull/2356/checks?check_run_id=10101893073)?

**Comment by whynowy** [comment]
@rdeusser - Thanks for submitting the PR! Could you also update the doc to include the changes? https://github.com/argoproj/argo-events/blob/master/docs/validating-admission-webhook.md

**Review by gabrielknot — APPROVED** [review]

**Review by whynowy — APPROVED** [review]
I will add the doc.

**Pull request merged**
