### PR TITLE
docs: Added Bitbucket Server docs

### PR DESCRIPTION
**Pull request by daniel-codefresh**
Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by daniel-codefresh** [comment]
Related issue: #1443

**Review by VaibhavPage — APPROVED** [review]
LGTM!

**Comment by daniel-codefresh** [comment]
@VaibhavPage the [doc](https://argoproj.github.io/argo-events/eventsources/setup/bitbucketserver/) was created successfully but for some reason I cannot see it in the `Setup` list in the `EventSources` menu.. Did I miss anything? Or is there anything else I should add?

**Comment by whynowy** [comment]
Need to add it to https://github.com/argoproj/argo-events/blob/master/mkdocs.yml.

**Comment by daniel-codefresh** [comment]
> Need to add it to https://github.com/argoproj/argo-events/blob/master/mkdocs.yml.

Thanks @whynowy ! Here is the PR: #1662

**Pull request merged**
