### PR TITLE
chore: Dockerfile compatible with all Architecture builds

### PR DESCRIPTION
**Pull request by mickkael**
Signed-off-by: mickkael <19755421+mickkael@users.noreply.github.com>

Compiled successfully arm64 with this patched Dockerfile
https://hub.docker.com/r/mickkael/argo-events/tags

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by whynowy** [comment]
Thanks for your PR!

Instead of specifying the ARCH, I would expect to see it support multi-arch build automatically (#1190). Please let me know if you would like to take it.

**Comment by mickkael** [comment]
I'll work on the pipeline to make a multi-arch container. I do it already locally with an argo workflow and steps for arm64/arm/amd64, and mplatform/manifest-tool to have the multi-arch manifest. But we need this Dockerfile anyway as a starting point for each architecture build

**Comment by whynowy** [comment]
> I'll work on the pipeline to make a multi-arch container. I do it already locally with an argo workflow and steps for arm64/arm/amd64, and mplatform/manifest-tool to have the multi-arch manifest. But we need this Dockerfile anyway as a starting point for each architecture build.
> 
> Hey @whynowy , what CI is used to build and push argo-events ? I can't find anything in the repo.

We used to support multi-arch build before, but there were some issues that pushing a large multi-arch image took too long and it often made the connection to image registry drop, so we removed that support. Now we have combined multiple images to one, I think probably we should get it back - but I'm not sure if the issue still exists, since current image is still large.

You could refer to https://github.com/argoproj/argo-events/pull/843.

The workflow to build images is https://github.com/argoproj/argo-events/blob/master/.github/workflows/release.yml.

**Comment by mickkael** [comment]
I see. It's Github actions. It has only x86 hosts available, so everything else is emulated, and takes ages to compile. I'll dig and see if I can achieve something.
in the meantime, I have published the multmanifest image on my repo for anyone who needs
docker.io/mickkael/argo-events:latest

**Comment by mickkael** [comment]
Close as #1218 supersedes it.

**Pull request closed without merging**
