### PR TITLE
chore: Upgrade sprig templating library to v3.2.0

### PR DESCRIPTION
**Pull request by tomgoren**
Solves: https://github.com/argoproj/argo-events/issues/1042

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by whynowy** [comment]
Please fix DCO and run `go mod tidy`.

**Review by whynowy — APPROVED** [review]
LGTM, thanks for fixing it!

**Comment by bensusman** [comment]
Sorry for maybe a dumb question: 
After reviewing the release announcements, I didn't see this bug included in a release/rc: https://github.com/argoproj/argo-events/releases

Is this fix still queued up or is there a stable version of Argo Events that already include this fix?

**Comment by whynowy** [comment]
It will be in v1.3.0 (currently v1.3.0-rc4). @bensusman

**Pull request merged**
