### PR TITLE
chore: upgrade kube libraries to 0.20.4

### PR DESCRIPTION
**Pull request by sbose78**
Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by whynowy** [comment]
Workflows and Events have the agreement that we would like to stay 1 major version behind of the latest, which is v1.19.x.

**Comment by sbose78** [comment]
Gotcha, thanks. 

Curious, what's the reason for this? :)

**Comment by whynowy** [comment]
> Gotcha, thanks.
> 
> Curious, what's the reason for this? :)

Just don't want to be too aggressive, and it's a safer option.

**Comment by sbose78** [comment]
Got it, thanks.

**Pull request closed without merging**
