### PR TITLE
fix: update kubernetes labels to comply with recommended labels

### LINKED ISSUE #3172: Kustomizations don't comply with kubernetes recommended labels
**Describe the bug**
The argo-events manifests use the old style of labels of `app` which is now preferred to be set to `app.kubernetes.io/name` per the [Kubernetes label recommendations](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/).

**Environment (please complete the following information):**
 - Kubernetes: v1.26.14
 - Argo: v2.9.4
 - Argo Events: v1.9.3

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by therealdwright**
This commit updates all docs, manifests and tests to comply with the
official [Kubernetes Recommended Labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/)

Signed-off-by: Daniel Wright <dan@dwright.io>

Closes #3172

Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

### CODE REVIEW

**Comment by therealdwright** [comment]
> could you test and comment what will be the behaviors and anything needs to do?

Yeah - we have forked the manifests are running this version of the labels and everything works. You are correct that you will either need to run some variant of `kubectl replace` or `kubectl apply --force`

**Comment by whynowy** [comment]
I'm hesitating about this change - definitely it's reasonable, even though it requires a force update. 

I'm thinking that we also should add recommended labels to the orchestrated resources - the deployments generated for event sources and sensors.

**Comment by therealdwright** [comment]
> I'm thinking that we also should add recommended labels to the orchestrated resources - the deployments generated for event sources and sensors.

I will have to spend a bit more time understanding the code if this is something you really want me to do as part of this PR.

Really the goal here was to make the world a better place as the `app` and `k8s-app` are pretty legacy at this stage, we maintain our own manifests to avoid using these legacy labels.

**Comment by whynowy** [comment]
> > I'm thinking that we also should add recommended labels to the orchestrated resources - the deployments generated for event sources and sensors.
> 
> I will have to spend a bit more time understanding the code if this is something you really want me to do as part of this PR.
> 
> Really the goal here was to make the world a better place as the `app` and `k8s-app` are pretty legacy at this stage, we maintain our own manifests to avoid using these legacy labels.

Appreciate if you would like to spend time on it, let me know!

**Pull request closed without merging**
