### PR TITLE
Support configuring argo CLI args when using argo workflow trigger.

### LINKED ISSUE #1257: Support Argo resume/stop node field selectors
**Is your feature request related to a problem? Please describe.**

Using Argo CLI to resume via the `argoWorkflow` trigger as documented [here](https://argoproj.github.io/argo-events/sensors/triggers/argo-workflow/#argo-cli) does not support the use of [node field selectors](https://argoproj.github.io/argo-workflows/node-field-selector/).

**Describe the solution you'd like**

I would like it to be possible to configure node field selectors when using the `argoWorkflow` trigger template.

**Describe alternatives you've considered**
n/a

**Additional context**

As seen [here](https://github.com/argoproj/argo-events/blob/master/sensors/triggers/argo-workflow/argo-workflow.go#L162) only the Workflow name can be passed in.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by lacarvalho91**
Closes #1257 

- Makes it possible to perform assertions on the argo command that is executed.
- Allows configuring args to be passed to the argo CLI.

Not really expecting this to be complete, but looking for guidance.

One thing I'd like to know is, will this new field I've added `args` be able to be generated from parameters? I couldn't work it out. Or if there is somewhere I can test that I'd be keen to know so I can do that.

### CODE REVIEW

**Comment by lacarvalho91** [comment]
I've run `make codegen` but the Codegen part still fails :/

**Comment by lacarvalho91** [comment]
Hmm the codegen seems to have also added loads of newlines in the docs :confused:

**Comment by lacarvalho91** [comment]
@alexec I just tried `make codegen -B` and it still seems to add newlines after each line in the docs. I'm not sure which tests need fixing? The only PR check that is failing is the codegen one from what I can see,

I'll try running codegen from a different machine tomorrow and see if that has a different outcome.

Do you have any idea about this?

>One thing I'd like to know is, will this new field I've added args be able to be generated from parameters? I couldn't work it out. Or if there is somewhere I can test that I'd be keen to know so I can do that.

**Comment by whynowy** [comment]
> @alexec I just tried `make codegen -B` and it still seems to add newlines after each line in the docs. I'm not sure which tests need fixing? The only PR check that is failing is the codegen one from what I can see,
> 
> I'll try running codegen from a different machine tomorrow and see if that has a different outcome.
> 
> Do you have any idea about this?
> 
> > One thing I'd like to know is, will this new field I've added args be able to be generated from parameters? I couldn't work it out. Or if there is somewhere I can test that I'd be keen to know so I can do that.

What is your `pandoc` version? Compare with https://github.com/argoproj/argo-events/blob/master/.github/workflows/ci.yaml#L46, if yours is newer, update the ci.yaml, otherwise update yours.

**Comment by alexec** [comment]
@whynowy I don't think updating the ci.yaml on a fork will have affect until merged. I think PRs always run the ci.yaml on main/master branch.

**Comment by whynowy** [comment]
> @whynowy I don't think updating the ci.yaml on a fork will have affect until merged. I think PRs always run the ci.yaml on main/master branch.

No, it respects the PR's change. See https://github.com/argoproj/argo-events/pull/1672

**Comment by lacarvalho91** [comment]
Thanks guys, looks like I had an old version of `pandoc` installed - good call @whynowy.

The diff looks much better now :smile: so I think this is ready for review.

I'm still not clear on:
>will this new field I've added args be able to be generated from parameters?

As I'm hoping to be able to populate this new field using values from an event, using a `dataTemplate` parameter.

**Review by whynowy — APPROVED** [review]
LGTM, thanks for adding this feature!

**Comment by whynowy** [comment]
@lacarvalho91 - thanks for 

> Thanks guys, looks like I had an old version of `pandoc` installed - good call @whynowy.
> 
> The diff looks much better now 😄 so I think this is ready for review.
> 
> I'm still not clear on:
> 
> > will this new field I've added args be able to be generated from parameters?
> 
> As I'm hoping to be able to populate this new field using values from an event, using a `dataTemplate` parameter.

Not very clean what that means, could you give more detail?

**Comment by lacarvalho91** [comment]
@whynowy yeah sorry tricky to articulate :sweat_smile:. I'm hoping to be able to use parameter templating as shown here: https://argoproj.github.io/argo-events/tutorials/02-parameterization/#sprig-templates to be able to dynamically populate the `args` field that I added in this PR, using data from the incoming event.

**Comment by lacarvalho91** [comment]
@whynowy also wondering if you have any idea when this will be released? Looks like it didn't make it for `1.6.2`

**Comment by lacarvalho91** [comment]
Just seen it was released in 1.6.3, thanks!

**Pull request merged**
