### PR TITLE
fix: kafka schema registry

### PR DESCRIPTION
**Pull request by jwillker**
Checklist:

* [x] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

Move SchemaRegistry validation to the right place, to avoid getting only once the Avro file from the registry.

Fix: https://github.com/argoproj/argo-events/issues/2422

### CODE REVIEW

**Comment by whynowy** [comment]
@jwillker - It looks good to me, could you remove the empty line as the `lint` error mentioned?

**Comment by whynowy** [comment]
Also, don't forget to sign off your commit as the `DCO` check mentioned.

**Comment by jwillker** [comment]
All done @whynowy !

**Review by whynowy — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
