### PR TITLE
fix: update slack-go version. Fixes #966

### LINKED ISSUE #966: Slack eventsource encounters bug in slack-go
**Describe the bug**

**To Reproduce**
1. Clicking on a Slack button to trigger an event
2. Get a message either about "cannot do this" or "error 500 received"
3. Logs from container show:

```
failed to parse interaction event:  json: cannot unmarshal object into Go struct field InteractionCallback.state of type string

failed to parse interaction event
github.com/argoproj/argo-events/eventsources/sources/slack.(*Router).handleInteraction
	/home/runner/work/argo-events/argo-events/eventsources/sources/slack/start.go:216
github.com/argoproj/argo-events/eventsources/sources/slack.(*Router).HandleRoute
	/home/runner/work/argo-events/argo-events/eventsources/sources/slack/start.go:126
github.com/argoproj/argo-events/eventsources/common/webhook.startServer.func2
	/home/runner/work/argo-events/argo-events/eventsources/common/webhook/webhook.go:148
net/http.HandlerFunc.ServeHTTP
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:2041
github.com/gorilla/mux.(*Router).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:2836
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:1924
runtime.goexit
	/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/asm_amd64.s:1373","stacktrace":"github.com/argoproj/argo-events/eventsources/sources/slack.(*Router).HandleRoute
	/home/runner/work/argo-events/argo-events/eventsources/sources/slack/start.go:128
github.com/argoproj/argo-events/eventsources/common/webhook.startServer.func2
	/home/runner/work/argo-events/argo-events/eventsources/common/webhook/webhook.go:148
net/http.HandlerFunc.ServeHTTP
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:2041
github.com/gorilla/mux.(*Router).ServeHTTP
	/home/runner/go/pkg/mod/github.com/gorilla/mux@v1.7.3/mux.go:212
net/http.serverHandler.ServeHTTP
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:2836
net/http.(*conn).serve
	/opt/hostedtoolcache/go/1.14.7/x64/src/net/http/server.go:1924
```

**Expected behavior**
Expected event from Slack to be parsed and a new event generated via slack eventsource

**Screenshots**
Screen Shot 2020-11-20 at 3 06 25 PM

**Environment (please complete the following information):**
 - Kubernetes: v1.9.5
 - Argo: v2.10.2
 - Argo Events: v1.0.0

**Additional context**
This appears to be the same as described in https://github.com/slack-go/slack/issues/816 and in version 0.7.1 which is patched and released in slack-go 0.7.1

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

### PR DESCRIPTION
**Pull request by StephenWeber**
Update slack-go to newest 0.7.1 version to fix a bug in the JSON received from Slack.

### CODE REVIEW

**Comment by whynowy** [comment]
@StephenWeber - have you tried the new version and it fixed the problem?

**Comment by StephenWeber** [comment]
@whynowy we're working on getting that done locally, I'd just been out all last week and just coming back to this. Will let you know, and get the tests updated.

**Comment by StephenWeber** [comment]
The reproduction for this is really challenging, but we have this PR deployed and have an opportunity to try it out this week. For the type of workflows we'll be running, we've always had this issue show up, so we should know if this fixes our problem soon.

**Comment by whynowy** [comment]
@StephenWeber - I already upgraded slack-go to version 0.7.4 in https://github.com/argoproj/argo-events/pull/991.

**Pull request closed without merging**
