### PR TITLE
feat: Azure Service Bus as a Trigger

### LINKED ISSUE #2279: Support for Azure Service Bus as a Trigger
**Is your feature request related to a problem? Please describe.**
It would be nice to be able to have support for Azure Service Bus as a trigger

**Describe the solution you'd like**
Able to send messages to a Azure Service Bus queue

**Describe alternatives you've considered**
Azure Event Hub is too overkill

### PR DESCRIPTION
**Pull request by omBratteng**
Signed-off-by: Ole-Martin Bratteng <1681525+omBratteng@users.noreply.github.com>
Checklist:

* [ ] My organization is added to [USERS.md](https://github.com/argoproj/argo-events/blob/master/USERS.md).

Closes #2279

### CODE REVIEW

**Comment by whynowy** [comment]
@omBratteng - is it ready for review?

**Comment by omBratteng** [comment]
I don't remember. I think it was more or less completed, just had some final testing to do. I'll see if I can get this ready for review shortly.

**Comment by omBratteng** [comment]
@whynowy it is now ready for review

**Review by whynowy — APPROVED** [review]
LGTM, thanks!

**Comment by whynowy** [comment]
@omBratteng - Sorry for the delay! Could you fix the conflict and then it's good to go!

**Comment by omBratteng** [comment]
Awesome, I'll fix the issue shortly

**Comment by omBratteng** [comment]
@whynowy rebased and re-ran codegen to fix the conflict

**Comment by whynowy** [comment]
Thank you @omBratteng

**Comment by omBratteng** [comment]
Awesome. Quick question, when is the next planned release?

**Pull request merged**
